### ISSUE TITLE
扫描过程中按手机home键，重新切换到扫描页面，显示异常

### ISSUE THREAD

**Issue by lifw** [yiruchujian/QrCodeCreationRecognition#1]
扫描过程中，如果按home键，程序进入后台，然后重新切换到扫描页面，会增加一条多余的横线，重复几次（按home键-切换扫描页面），会增加多条横线，并且横线的移动速度也加快不少

**Comment by yiruchujian** [comment]
> 扫描过程中，如果按home键，程序进入后台，然后重新切换到扫描页面，会增加一条多余的横线，重复多次（按home键-切换扫描页面），会增加多条横线，并且横线的移动速度也加快过多

**Comment by chujiandaochuxia** [comment]
已修改
